### ISSUE TITLE
Can't install pods

### ISSUE THREAD

**Issue by callengene** [tapkey/ios-sample-app#2]
pod install
Analyzing dependencies
Traceback (most recent call last):
        10343: from /usr/local/bin/pod:23:in `<main>'
        10342: from /usr/local/bin/pod:23:in `load'
        10341: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
        10340: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
        10339: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
        10338: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:52:in `run'
        10337: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:160:in `install!'
        10336: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
         ... 10331 levels...
            4: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.19.0/lib/xcodeproj/config.rb:61:in `initialize'
            3: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.19.0/lib/xcodeproj/config.rb:61:in `each'
            2: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.19.0/lib/xcodeproj/config.rb:62:in `block in initialize'
            1: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.19.0/lib/xcodeproj/config.rb:62:in `new'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:94:in `initialize': stack level too deep (SystemStackError)
        9: from /usr/local/bin/pod:23:in `<main>'
        8: from /usr/local/bin/pod:23:in `load'
        7: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
        6: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
        5: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:324:in `run'
        4: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:337:in `rescue in run'
        3: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:396:in `handle_exception'
        2: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:66:in `report_error'
        1: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface/error_report.rb:34:in `report'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface/error_report.rb:34:in `force_encoding': can't modify frozen String (FrozenError)

**Comment by L6Echo** [comment]
I am not able to reproduce this issue yet. It seems not necessary to be an issue with the project itself but a problem with the local cocoapod installation. Which mac os version do you use? Do you use the default os ruby version or do you have a custom installation?

The project contains also ein bundler file. Can you try to use this instead of a global cocoapod installation?

```
bundle install
bundle exec pod install
```

**Comment by callengene** [comment]
Hi, you're probably right, it's my setup causing the problem, 
I'm using macOS BigSur
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
Pod version 1.10.0
After running 
bundle install
bundle exec pod install
bundler: failed to load command: pod (/usr/local/bin/pod)
FrozenError: can't modify frozen String
  /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface/error_report.rb:34:in `force_encoding'
  /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface/error_report.rb:34:in `report'
  /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:66:in `report_error'
  /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:396:in `handle_exception'
  /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:337:in `rescue in run'
  /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:324:in `run'
  /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
  /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
  /usr/local/bin/pod:23:in `load'
  /usr/local/bin/pod:23:in `<top (required)>'
