### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by Psiiirus** [tapkey/ios-sample-app#5]
Hi,
I'm trying to compile this example but it wont do because it says
-> No such module 'TapkeyMobileLib'

yes i did pod install. :-)

**Comment by L6Echo** [comment]
Hi,

we updated the iOS Sample App right now to the latest TapkeyMobileLib version.

Please can you retry to compile the app and please make sure to use bundler to install and run the current cocoapods version. (See the updated README).

Older Cocoapods versions are known to not support the new xcframework format and this might have caused your described issue.

**Comment by Psiiirus** [comment]
its working now! thanks i guess the bundler did the trick
